"""create_all_tables

Revision ID: 969e26027a08
Revises: 
Create Date: 2026-05-06 23:53:52.677355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969e26027a08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_jobs_job_id'), 'content_jobs', ['job_id'], unique=True)
    op.create_table('event_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_clusters_cluster_id'), 'event_clusters', ['cluster_id'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('lookback_hours', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('source_errors_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_run_id'), 'ingestion_runs', ['run_id'], unique=True)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('authority_weight', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_documents_ingestion_run_id'), 'raw_documents', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_id'), 'raw_documents', ['source_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('authority_weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=True)
    op.create_table('cluster_documents',
    sa.Column('cluster_id_fk', sa.Integer(), nullable=False),
    sa.Column('document_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id_fk'], ['event_clusters.id'], ),
    sa.ForeignKeyConstraint(['document_id_fk'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('cluster_id_fk', 'document_id_fk')
    )
    op.create_table('draft_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('long_title', sa.Text(), nullable=False),
    sa.Column('long_body', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('short_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_packages_job_id'), 'draft_packages', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rewind', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('qa_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('factual_accuracy_score', sa.Integer(), nullable=False),
    sa.Column('viewpoint_clarity_score', sa.Integer(), nullable=False),
    sa.Column('sources_verified', sa.Boolean(), nullable=False),
    sa.Column('within_time_window', sa.Boolean(), nullable=False),
    sa.Column('claims_supported', sa.Boolean(), nullable=False),
    sa.Column('long_short_consistent', sa.Boolean(), nullable=False),
    sa.Column('failed_checks_json', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_reviews_job_id'), 'qa_reviews', ['job_id'], unique=True)
    op.create_table('research_packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('primary_source_summary', sa.Text(), nullable=False),
    sa.Column('source_briefs_json', sa.Text(), nullable=False),
    sa.Column('timeline_json', sa.Text(), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('open_questions_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_packets_job_id'), 'research_packets', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_packets_job_id'), table_name='research_packets')
    op.drop_table('research_packets')
    op.drop_index(op.f('ix_qa_reviews_job_id'), table_name='qa_reviews')
    op.drop_table('qa_reviews')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_draft_packages_job_id'), table_name='draft_packages')
    op.drop_table('draft_packages')
    op.drop_table('cluster_documents')
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_raw_documents_source_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_ingestion_run_id'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_ingestion_runs_run_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_event_clusters_cluster_id'), table_name='event_clusters')
    op.drop_table('event_clusters')
    op.drop_index(op.f('ix_content_jobs_job_id'), table_name='content_jobs')
    op.drop_table('content_jobs')
    # ### end Alembic commands ###
